IDIR =../include
CC=gcc
CFLAGS=-I$(IDIR)

ODIR=obj
LDIR=../lib

LIBS=-lm

_DEPS = contadores.h teclado.h fantasma.h score.h
DEPS = $(patsubst %,$(IDIR)/%,$(_DEPS))

_OBJ = contadores.o teclado.o fantasma.o score.o main.o
OBJ = $(patsubst %,$(ODIR)/%,$(_OBJ))

$(ODIR)/%.o: %.c $(DEPS)
			$(CC) -c -o $@ $^ $(CFLAGS) $(LIBS)

.PHONY: clean

clean: 
		rm -f $(ODIR)/*.o *~ core $(INCDIR)/*~  